export const selectTableData = (state) => state.category.tableData;
export const selectSelectedClue = (state) => state.category.selectedClue;
export const selectIsModalOpen = (state) => state.category.isModalOpen;
export const selectClickedClues = (state) => state.category.clueClicked;
export const selectPoints = (state) => state.category.points;
export const selectIsAnswerCorrect = (state) => state.category.isAnswerCorrect;
export const selectUser = (state) => state.category.user;
export const selectStatus = (state) => state.category.status;
export const selectTimer = (state) => state.category.timer;
